
class Settings:
    BLOCK_SIZE = 32
    WORLD_MAP_WIDTH = 5
    WORLD_MAP_HEIGHT = 5

    GAME_WINDOW_WIDTH = 30 * BLOCK_SIZE
    GAME_WINDOW_HEIGHT = 20 * BLOCK_SIZE

    WINDOW_WIDTH = GAME_WINDOW_WIDTH + 200
    WINDOW_HEIGHT = GAME_WINDOW_HEIGHT

